export const
  BAKER = 'BAKER',
  CASHIER = 'CASHIER',
  SPOTTER = 'SPOTTER',
  WAREHOUSE = 'WAREHOUSE',
  BRANCH_MGR = 'BRANCH_MANAGER',
  DISTRICT_MGR = 'DISTRICT_MANAGER',
  FRANCHISEE = 'FRANCHISEE',
  ACCOUNTING = 'ACCOUNTING',
  OWNER = 'OWNER';
